### ISSUE TITLE
Matches Not appearing

### ISSUE THREAD

**Issue by tujituji1** [ClubPress/wp-club-manager#10]
Hello, I have an issue, I'm sure it's not because of theme, because I've tried several themes which has plugin support. I've deactivated all the plugins but still same...
Also every other features work fine, withour any problems...
It says: No matches yet. when I've added three matches...
By the way I'm sure I dont have short code related issue because I've checked all option...

**Comment by sergiovisual** [comment]
I think its a bug. Only the default club, selected in the configuration, show the matches results.
