### ISSUE TITLE
Extension to BuddyBoss

### ISSUE THREAD

**Issue by tonymeltone** [ClubPress/wp-club-manager#23]
Hi -

Have you considered writing to a member site like BuddyBoss?  It would be great if the player information from club manager would be displayed in the member profile.  It would also be great if club manager published updates to the activity feed of BuddyBoss.  

They are built on wordpress, and also just released a restapi.

**Comment by roofdog** [comment]
Thanks for the suggestion. I haven't seen BuddyBoss before, looks interesting.

To be honest though I have so much in the pipeline I can't see me getting round to an integration anytime soon but it is something I will look into in the future.
