### ISSUE TITLE
Import Staff: cannot understand which template is right

### ISSUE THREAD

**Issue by rikbon** [ClubPress/wp-club-manager#28]
Hi team,
 I'm facing an issue while importing staff.
The caption in the first stage of the import workflow states: _Staff need to be defined with columns in a specific order (6 columns)_ 

![image](https://user-images.githubusercontent.com/38118285/96155870-b70e6780-0f10-11eb-98e3-8016e0cf46bf.png)

When I download the template, it has 9 columns (First Name | Last Name | Jobs | Team | Season | Date of Birth | Nationality | Email | Phone). 

![image](https://user-images.githubusercontent.com/38118285/96155689-81697e80-0f10-11eb-882d-baec632be61e.png)

In the second step of the import, the data recap screen, it show 7 columns 
![image](https://user-images.githubusercontent.com/38118285/96155645-71519f00-0f10-11eb-88d2-cf10ea22e4e4.png)

and when i click Import, it return **0 imported 19 skipped**

![image](https://user-images.githubusercontent.com/38118285/96155787-9fcf7a00-0f10-11eb-8029-69343f5a21e5.png)

So, what's the correct template? how many columns?

thanks in advance

**Comment by roofdog** [comment]
Hi rikbon,

That is a bit of a mess, I'll get it cleaned up in the next release.

The correct input should be:

First Name | Last Name | Jobs | Date of Birth | Nationality | Email | Phone

Hope that helps :)
